version: '3'

services:
  db:
    image: postgres
  web:
    restart: on-failure
    container_name: invoice
    build: .
    command: ./manage.py runserver 0.0.0.0:8000 --insecure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db