# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-12 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('mol', models.CharField(default='', max_length=255)),
                ('eik', models.CharField(max_length=255)),
                ('dds', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_iban', models.CharField(max_length=255, null=True)),
                ('payment_swift', models.CharField(max_length=255, null=True)),
                ('payment_type', models.CharField(max_length=155, null=True)),
                ('payment_bank', models.CharField(max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
