# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_companyaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyaccess',
            name='users',
        ),
        migrations.AddField(
            model_name='companyaccess',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyaccess',
            name='invitation_date',
            field=models.DateField(auto_created=True),
        ),
    ]
