# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 10:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170817_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
