# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170922_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companytranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='companytranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelManagers(
            name='company',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='mol',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='CompanyTranslation',
        ),
    ]
