# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usersettings'),
        ('core', '0004_auto_20170927_1001'),
    ]

    operations = [
    ]
