# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170817_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyaccess',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
