# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170817_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccess',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
