# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20171007_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eik',
            field=models.CharField(max_length=255),
        ),
    ]
