# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-17 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170817_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccess',
            name='expire_on',
            field=models.DateField(),
        ),
    ]
