# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-08-18 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170817_1507'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyaccess',
            unique_together=set([('company', 'user')]),
        ),
    ]
