# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_company_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(1, 'Банков превод'), (2, 'В брой'), (3, 'С наложен платеж')], default=1),
        ),
    ]
