# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_company_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='payment_type',
            field=models.CharField(max_length=155),
        ),
    ]
