# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20171027_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_type_tr',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='payment_type',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
