# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20170808_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mol_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mol_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name_en',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name_es',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='measure_en',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='measure_es',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name_en',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name_es',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
