# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-06 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20170904_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_address_bg',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mol_bg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name_bg',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='measure_bg',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name_bg',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
