# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 09:56
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def run_update_money_rates(apps, schema_editor):
    call_command("update_exchange_rates", "--all", verbosity=1, interactive=False)

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20170920_1805'),
    ]

    operations = [
        migrations.RunPython(run_update_money_rates),
    ]
