# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_auto_20170922_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'invoices_invoiceitem_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='InvoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('client_address', models.CharField(db_index=True, max_length=255)),
                ('client_mol', models.CharField(max_length=255)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('accepted_by', models.CharField(blank=True, max_length=255)),
                ('payment_type', models.CharField(blank=True, max_length=255)),
                ('payment_bank', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'db_table': 'invoices_invoice_translation',
                'db_tablespace': '',
                'abstract': False,
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_mol',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_bank',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='invoicetranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='invoiceitemtranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='invoices.InvoiceItem'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicetranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceitemtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
