# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_auto_20170926_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitemtranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invoiceitemtranslation',
            name='master',
        ),
        migrations.AlterUniqueTogether(
            name='invoicetranslation',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='invoicetranslation',
            name='master',
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mol',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default='', max_length=155),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='InvoiceItemTranslation',
        ),
        migrations.DeleteModel(
            name='InvoiceTranslation',
        ),
    ]
