# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20170927_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma'), ('credit', 'Credit'), ('debit', 'Debit')], default='invoice', max_length=10),
        ),
    ]
