# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20170927_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_dds',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
