# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20171003_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='no_dds_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_bank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_iban',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_swift',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
