# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20171003_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accepted_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
