# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 04:52
from __future__ import unicode_literals

from django.db import migrations, models


def set_order_no(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    for invoice in Invoice.objects.all().iterator():
        count = 1
        for invoice_item in invoice.invoiceitem_set.all():
            invoice_item.order_no = count
            invoice_item.save()
            count += 1


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20171003_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='order_no',
            field=models.SmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.RunPython(set_order_no),
    ]
