# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20171004_2016'),
        ('invoices', '0014_invoiceitem_order_no'),
    ]

    operations = [
    ]
