# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_merge_20171005_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accepted_by_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address_tr',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_city_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_mol_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name_tr',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='no_dds_reason_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='note_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_bank_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_type_tr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='measure_tr',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='name_tr',
            field=models.CharField(max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
