# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20171007_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dds_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
