# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:30
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_auto_20171016_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ('pk',)},
        ),
        migrations.AddField(
            model_name='invoice',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='invoices_in_search__046699_gin'),
        ),
    ]
