# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 11:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_auto_20171020_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='dds_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
