# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0028_auto_20171025_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type_tr',
        ),
    ]
