# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_remove_invoice_payment_type_tr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_type',
        ),
    ]
