# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_auto_20171027_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='ref_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
