# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 18:24
from __future__ import unicode_literals

from django.db import migrations, models

def no_null_values(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    for item in Invoice.objects.all():
        item.no_dds_reason = ''
        item.no_dds_reason_tr = ''
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_invoice_ref_number'),
    ]

    operations = [
        migrations.RunPython(no_null_values),
        migrations.AlterField(
            model_name='invoice',
            name='no_dds_reason',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='no_dds_reason_tr',
            field=models.CharField(default='', max_length=255),
        ),
    ]
