# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_auto_20171028_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='name_tr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
