# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_auto_20171030_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
