# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_eik', models.CharField(max_length=255)),
                ('receiver_dds', models.CharField(max_length=255)),
                ('receiver_city', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_mol', models.CharField(max_length=255)),
                ('provider_name', models.CharField(max_length=255)),
                ('provider_eik', models.CharField(max_length=255)),
                ('provider_dds', models.CharField(max_length=255)),
                ('provider_city', models.CharField(max_length=255)),
                ('provider_address', models.CharField(max_length=255)),
                ('provider_mol', models.CharField(max_length=255)),
                ('invoice_no', models.PositiveIntegerField(blank=True)),
                ('proforma_no', models.PositiveIntegerField(blank=True)),
                ('released_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('tax_event_at', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('payment_type', models.CharField(max_length=255)),
                ('payment_iban', models.CharField(max_length=255)),
                ('payment_swift', models.CharField(max_length=255)),
                ('payment_bank', models.CharField(max_length=255)),
                ('tax_base', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('created_by', models.CharField(max_length=255)),
                ('accepted_by', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('quantity', models.PositiveIntegerField(blank=True)),
                ('measure', models.CharField(max_length=55)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('discount', models.FloatField(blank=True)),
                ('inv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
    ]
