# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-29 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(db_index=True, max_length=255)),
                ('client_eik', models.CharField(db_index=True, max_length=255)),
                ('client_dds', models.CharField(blank=True, max_length=255)),
                ('client_city', models.CharField(max_length=255)),
                ('client_address', models.CharField(db_index=True, max_length=255)),
                ('client_mol', models.CharField(max_length=255)),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma')], default='invoice', max_length=10)),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('released_at', models.DateField(auto_now_add=True, null=True)),
                ('taxevent_at', models.DateField(auto_now_add=True, null=True)),
                ('payment_type', models.CharField(blank=True, max_length=255)),
                ('payment_iban', models.CharField(blank=True, max_length=255)),
                ('payment_swift', models.CharField(blank=True, max_length=255)),
                ('payment_bank', models.CharField(blank=True, max_length=255)),
                ('dds_percent', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('accepted_by', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField()),
                ('no_dds_reason', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
            options={
                'ordering': ('-released_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('quantity', models.FloatField(blank=True, default=1)),
                ('measure', models.CharField(blank=True, max_length=55)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('company', 'invoice_type', 'number')]),
        ),
    ]
