# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20160906_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
