# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20160906_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma')], default='invoice', max_length=10),
        ),
    ]
