# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20160906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='proforma_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
