# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20160907_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='inv',
            new_name='invoice',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='released_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_event_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
