# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_last_updated'),
        ('invoices', '0007_auto_20160919_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='provider_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provider_city',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provider_dds',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provider_eik',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provider_mol',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
