# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_remove_invoice_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no_dds_reason',
            field=models.CharField(default='', max_length=255),
        ),
    ]
