# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_invoice_no_dds_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='no_dds_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
