# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-05 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170605_0826'),
        ('invoices', '0011_auto_20170604_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
