# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_address',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_city',
            new_name='client_city',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_dds',
            new_name='client_dds',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_eik',
            new_name='client_eik',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_mol',
            new_name='client_mol',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='receiver_name',
            new_name='client_name',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='total',
        ),
    ]
