# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20170619_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_base',
            new_name='dds_percent',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax_percent',
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
