# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_auto_20170619_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='client_dds',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
