# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_auto_20170619_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='measure',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
