# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_auto_20170619_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tax_event_at',
            new_name='taxevent_at',
        ),
    ]
