# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-25 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_auto_20170619_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accepted_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_iban',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_swift',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
