# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_auto_20170625_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
