# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_auto_20170708_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
