# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-15 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_auto_20170715_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set([('company', 'invoice_type', 'number')]),
        ),
    ]
