# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-16 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_auto_20170715_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-released_at',)},
        ),
    ]
