---
- name: Generate nginx config
  template:
    src: nginx/webinvoices.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Checkout webinvoices app
  git: repo=git@github.com:kaloyanm/invoiceapp.git dest=/opt/webinvoices accept_hostkey=yes
  when: not deploy_in_vagrant

- name: Install webinvoices requirements.txt
  pip:
    executable: pip3
    requirements: /opt/webinvoices/requirements.txt

- name: Django migrate & collect static
  shell: cd /opt/webinvoices ; ./manage.py migrate --no-input && ./manage.py collectstatic --no-input

- name: Generate production config
  template:
    src: .productionenv
    dest: /opt/webinvoices/.productionenv
    owner: www-data
    group: www-data
    mode: 0640
  when: not deploy_in_vagrant

- include: install_restart_service.yml name=webinvoices-web
- include: install_restart_service.yml name=webinvoices-celery
- include: tasks/install_timer.yml name=webinvoices-currency-rates
