ยง---
- name: Generate nginx config
  template:
    src: nginx/webinvoices.conf
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
