# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='provider_dds',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
