# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='eik',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
