# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-04 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170604_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='is_default',
            new_name='default',
        ),
    ]
