# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-08 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170605_0826'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('default', 'user')]),
        ),
    ]
