#!/bin/bash

# pdf server
git submodule init
git submodule update
(cd external/html2pdf/ && npm install)

# node
npm install
npm run build:prod

# django
pip install -r requirements.txt
./manage.py migrate
./manage.py collectstatic --no-input
