#!/bin/bash

# node
npm install
npm run build:prod

# django
pip install -r requirements.txt
./manage.py migrate
./manage.py collectstatic --no-input


# pdf server
git submodule init
git submodule update
